version: '3.8'
services:
  projects:
    image: revizor_projects_back:1.0
    ports:
      - "8787:8787"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=postgres
      - SERVE_PORT=8787
    networks:
      - projects_network
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - projects_network
    ports:
      - "5432:5432"

volumes:
  postgres_data:
networks:
  projects_network:
    driver: bridge