version: '3.8'
services:
  projects:
    build: .
    ports:
      - "127.0.0.1:8787:8787"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=postgres
      - DB_SSLMODE=disable
      - PORT=8787
      - HOST=0.0.0.0
    networks:
      - projects_network
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - POSTGRES_SSLMODE=disable
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - projects_network
    ports:
      - "127.0.0.1:5432:5432"

volumes:
  postgres_data:
networks:
  projects_network:
    driver: bridge